In [1]:
import os
import pandas as pd
import altair as alt
import numpy as np
from vega_datasets import data

In [2]:
root = '/Users/cynthiaxu/Documents/MIDS/03_2023 Fall/209 Data Visualization/209-ds-salaries-viz-project/'
folder = 'data'

data_path = os.path.join(root, folder)
data_path

'/Users/cynthiaxu/Documents/MIDS/03_2023 Fall/209 Data Visualization/209-ds-salaries-viz-project/data'

In [3]:
data_files = os.listdir(data_path)
data_files = [file for file in data_files if '2021' in file and '.csv' in file]
data_files

['Data Science Salary 2021 to 2023.csv', 'data_cleaned_2021.csv']

In [4]:
sal_df = pd.read_csv(os.path.join(data_path, data_files[0]))
skill_df = pd.read_csv(os.path.join(data_path, data_files[1]))

In [5]:
sal_df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size
0,2023,EN,FT,Applied Scientist,213660,USD,213660,US,L
1,2023,EN,FT,Applied Scientist,130760,USD,130760,US,L
2,2023,EN,FT,Data Quality Analyst,100000,USD,100000,NG,L
3,2023,EN,FT,Compliance Data Analyst,30000,USD,30000,NG,L
4,2023,EN,FT,Applied Scientist,204620,USD,204620,US,L
...,...,...,...,...,...,...,...,...,...
3756,2020,SE,FT,Principal Data Scientist,130000,EUR,148261,DE,M
3757,2020,SE,FT,Data Scientist,80000,EUR,91237,AT,S
3758,2020,SE,FT,Data Science Manager,190200,USD,190200,US,M
3759,2020,SE,FT,Machine Learning Engineer,40000,EUR,45618,HR,S
3760,2020,SE,FT,Data Scientist,412000,USD,412000,US,L

In [6]:
geo_file = [file for file in os.listdir(data_path) if 'countries' in file]

geo_df = pd.read_csv(os.path.join(data_path, geo_file[0]))
for i, col in enumerate(geo_df.columns):
    geo_df.iloc[:, i] = geo_df.iloc[:, i].str.replace('"', '')

geo_df['Alpha-2 code'] = geo_df['Alpha-2 code'].apply(lambda x: x.replace(' ', ''))

geo_df['Alpha-2 code'] = geo_df['Alpha-2 code'].astype(str)
geo_df['Latitude (average)'] = geo_df['Latitude (average)'].astype(float)
geo_df['Longitude (average)'] = geo_df['Longitude (average)'].astype(float)
geo_df

,Country,Alpha-2 code,Alpha-3 code,Numeric code,Latitude (average),Longitude (average)
0,Afghanistan,AF,AFG,4,33.0000,65.0
1,Albania,AL,ALB,8,41.0000,20.0
2,Algeria,DZ,DZA,12,28.0000,3.0
3,American Samoa,AS,ASM,16,-14.3333,-170.0
4,Andorra,AD,AND,20,42.5000,1.6
...,...,...,...,...,...,...
251,Wallis and Futuna,WF,WLF,876,-13.3000,-176.2
252,Western Sahara,EH,ESH,732,24.5000,-13.0
253,Yemen,YE,YEM,887,15.0000,48.0
254,Zambia,ZM,ZMB,894,-15.0000,30.0
255,Zimbabwe,ZW,ZWE,716,-20.0000,30.0

In [7]:
df = sal_df.merge(geo_df, left_on=['company_location'], right_on=['Alpha-2 code'], how='left')
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size,Country,Alpha-2 code,Alpha-3 code,Numeric code,Latitude (average),Longitude (average)
0,2023,EN,FT,Applied Scientist,213660,USD,213660,US,L,United States,US,USA,840,38.0000,-97.0000
1,2023,EN,FT,Applied Scientist,130760,USD,130760,US,L,United States,US,USA,840,38.0000,-97.0000
2,2023,EN,FT,Data Quality Analyst,100000,USD,100000,NG,L,Nigeria,NG,NGA,566,10.0000,8.0000
3,2023,EN,FT,Compliance Data Analyst,30000,USD,30000,NG,L,Nigeria,NG,NGA,566,10.0000,8.0000
4,2023,EN,FT,Applied Scientist,204620,USD,204620,US,L,United States,US,USA,840,38.0000,-97.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3761,2020,SE,FT,Principal Data Scientist,130000,EUR,148261,DE,M,Germany,DE,DEU,276,51.0000,9.0000
3762,2020,SE,FT,Data Scientist,80000,EUR,91237,AT,S,Austria,AT,AUT,40,47.3333,13.3333
3763,2020,SE,FT,Data Science Manager,190200,USD,190200,US,M,United States,US,USA,840,38.0000,-97.0000
3764,2020,SE,FT,Machine Learning Engineer,40000,EUR,45618,HR,S,Croatia,HR,HRV,191,45.1667,15.5000
3765,2020,SE,FT,Data Scientist,412000,USD,412000,US,L,United States,US,USA,840,38.0000,-97.0000

In [8]:
#jitter points
sigma = 2
df['latitude'] = df['Latitude (average)'].apply(lambda x: np.random.normal(x, sigma, 1)).astype(float)
df['longitude'] = df['Longitude (average)'].apply(lambda x: np.random.normal(x, sigma, 1)).astype(float)
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size,Country,Alpha-2 code,Alpha-3 code,Numeric code,Latitude (average),Longitude (average),latitude,longitude
0,2023,EN,FT,Applied Scientist,213660,USD,213660,US,L,United States,US,USA,840,38.0000,-97.0000,37.890880,-97.037861
1,2023,EN,FT,Applied Scientist,130760,USD,130760,US,L,United States,US,USA,840,38.0000,-97.0000,39.701956,-97.440170
2,2023,EN,FT,Data Quality Analyst,100000,USD,100000,NG,L,Nigeria,NG,NGA,566,10.0000,8.0000,10.405531,6.993634
3,2023,EN,FT,Compliance Data Analyst,30000,USD,30000,NG,L,Nigeria,NG,NGA,566,10.0000,8.0000,8.980460,10.784536
4,2023,EN,FT,Applied Scientist,204620,USD,204620,US,L,United States,US,USA,840,38.0000,-97.0000,38.341835,-94.614434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3761,2020,SE,FT,Principal Data Scientist,130000,EUR,148261,DE,M,Germany,DE,DEU,276,51.0000,9.0000,51.543627,7.625312
3762,2020,SE,FT,Data Scientist,80000,EUR,91237,AT,S,Austria,AT,AUT,40,47.3333,13.3333,47.543797,12.894960
3763,2020,SE,FT,Data Science Manager,190200,USD,190200,US,M,United States,US,USA,840,38.0000,-97.0000,37.927724,-96.947798
3764,2020,SE,FT,Machine Learning Engineer,40000,EUR,45618,HR,S,Croatia,HR,HRV,191,45.1667,15.5000,42.833458,20.836771
3765,2020,SE,FT,Data Scientist,412000,USD,412000,US,L,United States,US,USA,840,38.0000,-97.0000,38.621850,-98.159733

In [11]:
countries = alt.topo_feature(data.world_110m.url, 'countries')

background = alt.Chart(countries).mark_geoshape(
    fill='lightgray',
    stroke='white'
).project(
    "equirectangular"
).properties(
    width=800,
    height=400
)

points = alt.Chart(df, title = 'Location of Data Science Roles').mark_circle().encode(
    longitude='longitude:Q',
    latitude='latitude:Q',
    size=alt.value(10)
    # tooltip='name'
)

background + points

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/altair/utils/core.py:410: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/altair/utils/core.py:410: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/altair/utils/core.py:410: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.LayerChart(...)